name: Continuous Integration and Deployment

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest  
    container:
      image: node:23.4-alpine3.21  
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install

  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest  # Menggunakan runner Ubuntu
    services:
      docker:
        image: docker:19.03.12-dind  # Docker-in-Docker service
        options: --privileged  # Menambahkan opsi privileged agar Docker bisa berjalan dengan benar dalam container
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ vars.USERNAME }}/lanafatemani:latest .
      - name: Show Docker Images
        run: docker images
      - name: Push Docker image to DockerHub
        run: docker push ${{ vars.USERNAME }}/lanafatemani:latest

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest  # Menggunakan runner Ubuntu
    steps:
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y ssh
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ vars.USERNAME }}/lanafatemani:latest
            sudo docker stop lanafatemani || true
            sudo docker rm lanafatemani || true
            sudo docker run -d --name lanafatemani -p 3001:3000 ${{ vars.USERNAME }}/lanafatemani:latest
